// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE

import * as Fetch from "bs-fetch/src/Fetch.js";
import * as Json_decode from "@glennsl/bs-json/src/Json_decode.bs.js";

function conversation(json) {
  return /* record */[
          /* id */Json_decode.field("id", Json_decode.string, json),
          /* connector */Json_decode.field("connector", Json_decode.string, json),
          /* chatId */Json_decode.field("chatId", Json_decode.string, json),
          /* channel */Json_decode.field("channel", Json_decode.string, json),
          /* fallbacked */Json_decode.field("fallbacked", Json_decode.bool, json)
        ];
}

function result(json) {
  return /* record */[
          /* results */Json_decode.field("results", conversation, json),
          /* message */Json_decode.field("message", Json_decode.string, json)
        ];
}

var Decode = /* module */[
  /* conversation */conversation,
  /* result */result
];

function create(param) {
  return fetch("https://api.recast.ai/connect/v1/webhook/" + (String(param[/* channelid */1]) + "/conversations"), Fetch.RequestInit[/* make */0](/* Post */2, {
                          Authorization: param[/* token */0]
                        }, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* () */0)).then((function (prim) {
                    return prim.json();
                  })).then((function (json) {
                  var result$1 = result(json);
                  return Promise.resolve(result$1[/* results */0]);
                })).catch((function () {
                return Promise.resolve(undefined);
              }));
}

var Api = /* module */[/* create */create];

export {
  Decode ,
  Api ,
  
}
/* No side effect */
