// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

var component = ReasonReact.statelessComponent("Header");

function make(onClick, preferences, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: "RecastAppHeader",
                          style: {
                            backgroundColor: preferences[/* accentColor */0],
                            color: preferences[/* complementaryColor */1]
                          }
                        }, React.createElement("img", {
                              className: "RecastAppHeader--logo",
                              src: preferences[/* headerLogo */5]
                            }), React.createElement("p", {
                              className: "RecastAppHeader--title"
                            }, preferences[/* headerTitle */6]), React.createElement("button", {
                              className: "RecastAppHeader--btn",
                              onClick: onClick
                            }, React.createElement("img", {
                                  src: "https://cdn.recast.ai/webchat/close.svg"
                                })));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

export {
  component ,
  make ,
  
}
/* component Not a pure module */
