// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE

import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as App$ReactTemplate from "./App.bs.js";

var preferences = /* record */[
  /* accentColor */"#E05A47",
  /* complementaryColor */"#FFFFFF",
  /* botMessageColor */"#707070",
  /* botMessageBackgroundColor */"#F6F6F6",
  /* backgroundColor */"#FFFFFF",
  /* headerLogo */"https://cdn.recast.ai/webchat/webchat-logo.svg",
  /* headerTitle */"My awesome chatbot",
  /* botPicture */"https://cdn.recast.ai/webchat/bot.png",
  /* userPicture */"https://cdn.recast.ai/webchat/user.png",
  /* onboardingMessage */"Come speak to me!",
  /* expanderLogo */"https://cdn.recast.ai/webchat/webchat-logo.svg",
  /* expanderTitle */"Click on me!",
  /* conversationTimeToLive */24,
  /* openingType */"never",
  /* welcomeMessage */"Hello world !"
];

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, App$ReactTemplate.make(preferences, /* array */[])), "recast-webchat-div");

export {
  preferences ,
  
}
/*  Not a pure module */
