// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE

import * as Js_option from "bs-platform/lib/es6/js_option.js";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Js_primitive from "bs-platform/lib/es6/js_primitive.js";
import * as App$ReactTemplate from "./containers/app.bs.js";
import * as Preferences$ReactTemplate from "./models/preferences.bs.js";
import * as Conversation$ReactTemplate from "./models/conversation.bs.js";

var match = document.getElementById("recast-webchat");

var match$1;

if (match !== undefined) {
  var element = Js_primitive.valFromOption(match);
  match$1 = /* tuple */[
    Js_primitive.nullable_to_opt(element.getAttribute("channelid")),
    Js_primitive.nullable_to_opt(element.getAttribute("token"))
  ];
} else {
  match$1 = /* tuple */[
    undefined,
    undefined
  ];
}

var token = match$1[1];

var channelid = match$1[0];

if (channelid !== undefined && token !== undefined) {
  var credentials = /* record */[
    /* token */token,
    /* channelid */channelid
  ];
  Preferences$ReactTemplate.Api[/* fetch */0](credentials).then((function (preferences) {
              var preferences$1 = Js_option.getExn(preferences);
              return Conversation$ReactTemplate.getOrCreate(credentials).then((function (conversation) {
                            return Promise.resolve(/* tuple */[
                                        preferences$1,
                                        conversation
                                      ]);
                          }));
            })).then((function (param) {
            ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, App$ReactTemplate.make(param[0], credentials, /* array */[])), "recast-webchat-div");
            return Promise.resolve(/* () */0);
          })).catch((function (err) {
          console.log(err);
          console.log("Error while getting Channel's preferences or creating the conversation. Your credentials may are invalid");
          return Promise.resolve(/* () */0);
        }));
} else {
  console.log("ERROR: Could not find channelid and/or token credentials.");
}

export {
  channelid ,
  token ,
  
}
/* match Not a pure module */
