// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE

import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Js_primitive from "bs-platform/lib/es6/js_primitive.js";
import * as App$ReactTemplate from "./app.bs.js";
import * as Preferences$ReactTemplate from "./models/preferences.bs.js";

var match = document.getElementById("recast-webchat");

var match$1;

if (match !== undefined) {
  var element = Js_primitive.valFromOption(match);
  match$1 = /* tuple */[
    Js_primitive.nullable_to_opt(element.getAttribute("channelid")),
    Js_primitive.nullable_to_opt(element.getAttribute("token"))
  ];
} else {
  match$1 = /* tuple */[
    undefined,
    undefined
  ];
}

var token = match$1[1];

var channelid = match$1[0];

if (channelid !== undefined && token !== undefined) {
  var credentials = /* record */[
    /* token */token,
    /* channelid */channelid
  ];
  Preferences$ReactTemplate.Api[/* fetch */0](credentials).then((function (preferences) {
          if (preferences !== undefined) {
            ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, App$ReactTemplate.make(preferences, credentials, /* array */[])), "recast-webchat-div");
          } else {
            console.log("ERROR: Couldn't fetch the webchat preferences.");
          }
          return Promise.resolve(/* () */0);
        }));
} else {
  console.log("ERROR: Could not find channelid and/or token credentials.");
}

export {
  channelid ,
  token ,
  
}
/* match Not a pure module */
