// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE

import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as App$ReactTemplate from "./app.bs.js";
import * as Preferences$ReactTemplate from "./models/preferences.bs.js";

var credentials = /* record */[
  /* token */"4032443053b639457becb97af522eac9",
  /* channelid */"3080b46d-97b5-43e9-8f5b-762bade246a1"
];

Preferences$ReactTemplate.Api[/* fetch */0](credentials).then((function (preferences) {
        if (preferences !== undefined) {
          ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, App$ReactTemplate.make(preferences, credentials, /* array */[])), "recast-webchat-div");
        } else {
          console.log("ERROR: Couldn't fetch the webchat preferences.");
        }
        return Promise.resolve(/* () */0);
      }));

export {
  credentials ,
  
}
/*  Not a pure module */
