type preferences = {
  accentColor: string,
  complementaryColor: string,
  botMessageColor: string,
  botMessageBackgroundColor: string,
  backgroundColor: string,
  headerLogo: string,
  headerTitle: string,
  botPicture: string,
  userPicture: string,
  onboardingMessage: string,
  expanderLogo: string,
  expanderTitle: string,
  conversationTimeToLive: int,
  openingType: string,
  welcomeMessage: string,
};
